app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
    Route::get('/', 'PagesController@index');
    Route::get('About', 'PagesController@about');
    Route::get('Contacts', ['as' => 'contact', 'uses' => 'PagesController@contacts']);

    Route::post('Contacts', ['as' => 'contact_store', 'uses' => 'PagesController@store']);
    Route::get('Why-us', 'PagesController@why_us');

    Route::get('Properties', 'PagesController@properties');

    Route::get('edit', 'PagesController@edit');

    Route::get('images/{filename}', 'PropertyController@showImage')->where('filename', '(.*)')->name('images');
    // Authentication routes...
    Route::get('auth/login', 'Auth\AuthController@getLogin')->name('login');
    Route::post('auth/login', 'Auth\AuthController@postLogin')->name('login');


    // Registration routes...
    Route::get('/auth/register', 'Auth\AuthController@getRegister')->name('register');
    Route::post('/auth/register', 'Auth\AuthController@postRegister')->name('register');

    //reset password
    Route::get('password/reset/{token}', 'Auth\PasswordController@getReset')->name('reset');
    Route::post('password/reset', 'Auth\PasswordController@postReset')->name('reset');

    // Password reset link request routes...
    Route::get('password/email', 'Auth\PasswordController@getEmail')->name('email_password_reset_link');
    Route::post('password/email', 'Auth\PasswordController@postEmail')->name('email_password_reset_link');
});

Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/dashboard', 'PagesController@dashboard')->name('dashboard');
    Route::get('/dashboard/contacts', 'PagesController@viewContacts')->name('dashboard_contacts');
    Route::get('/dashboard/contacts/delete/{id}', 'PagesController@destroy')->name('dashboard_contacts_delete');
    Route::resource('/directors', 'DirectorController');
    Route::resource('/properties', 'PropertyController');
    Route::resource('/company', 'CompanyController');
    Route::resource('/carousel', 'CarouselController');
    Route::get('auth/logout', 'Auth\AuthController@getLogout')->name('logout');

});

resources/views/app.blade.php
<!--
@Author: Wilson Ndirangu <wndirangu>
@Date:   2016-06-25T21:53:42+03:00
@Email:  wnwillyndirangu@gmail.com
@Last modified by:   wndirangu
@Last modified time: 2016-08-11T19:23:59+03:00
@License: MIT
-->


<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Transcounty Investments Company</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="/js/jquery.min.js" type="text/javascript"></script>
    <!---font awesome --->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">


    <!-- Latest compiled JavaScript -->
    <script src="/js/bootstrap.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="/css/app.css">
    <script src="/js/app.js" type="text/javascript"></script>

    <!--- favicon--->
    <link href="/img/favicon.ico" rel="icon" type="image/x-icon"/>

</head>
<body>
<!--- Navigation bar--->
<div class="container-fluid">
    <div class="container">
        <div class="row">
            @yield('header')
            <nav class="navbar navbar-inverse">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand " href="{{ URL::action('PagesController@index') }}"><img
                                    class="tcil_logo" src="/img/logo.jpg"/> </a>
                    </div>
                    <div class="collapse navbar-collapse" id="myNavbar">
                        <ul class="nav navbar-nav  navbar-right">
                            <li class="{{ Request::is( '/') ? 'active' : '' }}"><a
                                        href="{{ URL::action('PagesController@index') }}"><span>Home</span></a></li>
                            <li class="{{ Request::is( 'About') ? 'active' : '' }}"><a
                                        href="{{ URL::action('PagesController@about') }}"><span>About us</span></a></li>
                            <li class="{{ Request::is( 'Properties') ? 'active' : '' }}"><a
                                        href="{{ action('PagesController@properties') }}"><span>Properties</span></a>
                            </li>
                            <li class="{{ Request::is( 'Why-us') ? 'active' : '' }}"><a
                                        href="{{ action('PagesController@why_us') }}"><span>Why us?</span></a></li>
                            <li class="{{ Request::is( 'Contacts') ? 'active' : '' }}"><a href="{{ route('contact') }}"><span>Contacts</span></a>
                            </li>
                        </ul>


                    </div>
                </div>
                <div class="row hidden-xs hidden-md-down">
                    <p>Real Estate dealers</p>
                </div>

            </nav>


            <!--- Navigation bar end--->
            <!---alert---->
            <div class="container">
                <div class="container-fluid">

                    <div class="row vertical-align hidden-md">
                        <div class="col-md-12 vcentre">
                            @yield('alert')

                        </div>
                    </div>
                </div>
            </div>

            @yield('content')


        <!---footer---->
            @yield('footer')


            <div class="container">
                <footer class="footer-distributed">
                    <div class="row">

                        <div class="footer-left col-md-4 ">

                            <h3>TCIC Ltd<span></span></h3>

                            <p class="footer-links">
                                <a href="{{ URL::action('PagesController@index') }}">Home</a>
                                ·
                                <a href="{{ URL::action('PagesController@about') }}">About-us</a>
                                ·
                                <a href="{{ URL::action('PagesController@properties') }}">Properties</a>
                                ·
                                <a href="{{ URL::action('PagesController@why_us') }}">Why-us?</a>
                                ·
                                <a href="{{ URL::action('PagesController@contacts') }}">Contacts</a>


                            </p>

                            <p class="footer-company-name">TCIC ltd &copy; {{Carbon\Carbon::now()->year}}</p>
                        </div>

                        <div class="footer-center col-md-4">
                            <div>
                                <p><span>      </span> Contacts</p>
                            </div>
                            <div>
                                <i class="fa fa-map-marker"></i>
                                <p><span></span>Kamulu, Kenya</p>
                            </div>

                            <div>
                                <i class="fa fa-phone"></i>
                                <p>0735940207/0739255945</p>
                            </div>

                            <div>
                                <i class="fa fa-envelope"></i>
                                <p style="color:#ffffff !important;">transcountyicl@gmail.com</p>
                            </div>

                        </div>

                        <div class="footer-right col-md-4">

                            <p class="footer-company-about">
                                <span>About the company</span>
                                TCICL is a leading real estate company in provision of prime, secure and affordable
                                properties to kenyans of all walks of life.
                            </p>

                            <div class="footer-icons">

                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-github"></i></a>

                            </div>

                        </div>
                    </div>
                </footer>

                <!---footer---->
            </div>
        </div>

    </div>


</div>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "Course",
  "name": "Transcounty Investments LTD ",
  "description": "Properties",
  "provider": {
    "@type": "Organization",
    "name": "TCIC",
    "sameAs": "http://www.transcountyivestments.co.ke/Properties"
  }
}

</script>

</body>

</html>

resources/views/auth.blade.php
<!--
 * Cytonn Technologies
 * @author Ndirangu Wilson <wndirangu@gmail.com>
--->

<!doctype html>
<html ng-app="dashboard" lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Board Management Application</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/auth.css">


</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">



                <!-- Authentication content loading -->
                @yield('content')
            </div>
        </div>
    </div>
</div>


</body>
</html>

resources/views/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title> Admin Dashboard</title>

    <!-- Bootstrap Core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/landing_dashboard.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/css/sb-admin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/css/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="index.html">Transcounty Admin</a>
        </div>
        <!-- Top Menu Items -->
        <ul class="nav navbar-right top-nav">


            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i
                            class="fa fa-user"></i> {{\Illuminate\Support\Facades\Auth::user()->name}} <b
                            class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li class="divider"></li>
                    <li>
                        <a href="{{route('logout')}}"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                    </li>
                </ul>
            </li>
        </ul>
        <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav side-nav">
                <li class="active">
                    <a href="{{route('dashboard')}}"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                </li>
                <li>
                    <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i
                                class="fa fa-fw fa fa-home"></i>Properties <i class="fa fa-fw fa-caret-down"></i></a>
                    <ul id="demo" class="collapse">
                        <li>
                            <a href="{{route('properties.index')}}">View Properties</a>
                        </li>
                        <li>
                            <a href="{{route('properties.create')}}">Add a Property</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="{{route('directors.index')}}"><i class="fa fa-fw fa-users"></i> Directors</a>
                </li>
                <li>
                    <a href="{{route('dashboard_contacts')}}"><i class="fa fa-fw fa fa-comments-o"></i> Messages</a>
                </li>
                <li>
                    <a href="{{route('company.index')}}"><i class="fa fa-fw fa-building-o"></i> Company</a>
                </li>
                <li>
                    <a href="{{route('carousel.index')}}"><i class="fa fa-fw fa-picture-o"></i> Carousel</a>
                </li>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </nav>
    @yield('content')

    <!-- /.container-fluid -->

    <!-- /#page-wrapper -->

</div>


<!-- /#wrapper -->

<!-- jQuery -->
<script src="/js/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/js/bootstrap.min.js"></script>

<!-- Morris Charts JavaScript -->
<script src="/js/raphael.min.js"></script>
<script src="/js/morris.min.js"></script>
<script src="/js/morris-data.js"></script>


@yield('script')
</body>

</html>