app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
    Route::get('/', 'PagesController@index');
    Route::get('About', 'PagesController@about');
    Route::get('Contacts', ['as' => 'contact', 'uses' => 'PagesController@contacts']);

    Route::post('Contacts', ['as' => 'contact_store', 'uses' => 'PagesController@store']);
    Route::get('Why-us', 'PagesController@why_us');

    Route::get('Properties', 'PagesController@properties');

    Route::get('edit', 'PagesController@edit');

    Route::get('images/{filename}', 'PropertyController@showImage')->where('filename', '(.*)')->name('images');
    // Authentication routes...
    Route::get('auth/login', 'Auth\AuthController@getLogin')->name('login');
    Route::post('auth/login', 'Auth\AuthController@postLogin')->name('login');


    // Registration routes...
    Route::get('/auth/register', 'Auth\AuthController@getRegister')->name('register');
    Route::post('/auth/register', 'Auth\AuthController@postRegister')->name('register');

    //reset password
    Route::get('password/reset/{token}', 'Auth\PasswordController@getReset')->name('reset');
    Route::post('password/reset', 'Auth\PasswordController@postReset')->name('reset');

    // Password reset link request routes...
    Route::get('password/email', 'Auth\PasswordController@getEmail')->name('email_password_reset_link');
    Route::post('password/email', 'Auth\PasswordController@postEmail')->name('email_password_reset_link');
});

Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/dashboard', 'PagesController@dashboard')->name('dashboard');
    Route::get('/dashboard/contacts', 'PagesController@viewContacts')->name('dashboard_contacts');
    Route::get('/dashboard/contacts/delete/{id}', 'PagesController@destroy')->name('dashboard_contacts_delete');
    Route::resource('/directors', 'DirectorController');
    Route::resource('/properties', 'PropertyController');
    Route::resource('/company', 'CompanyController');
    Route::resource('/carousel', 'CarouselController');
    Route::get('auth/logout', 'Auth\AuthController@getLogout')->name('logout');

});

app/Carousel.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model as Eloquent;

class Carousel extends Eloquent
{

    protected $table = "carousel";
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'image', 'title', 'description'
    ];

}

app/Http/Controllers/CarouselController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\CarouselFormRequest;
use App\Carousel;
use App\Repository\CarouselRepository;

class CarouselController extends Controller
{
    public $carouselRepository;

    public function __construct()
    {
        $this->carouselRepository = new CarouselRepository();
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view('dashboard.carousel.show')->with(['carousels' => Carousel::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('dashboard.carousel.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(CarouselFormRequest $request)
    {

        $this->carouselRepository->store($request);
        return \Redirect::route('carousel.index')->with('message', 'added carousel!');


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $carousel = Carousel::findOrFail($id);
        return view('dashboard.carousel.edit')->with(['carousel' => $carousel]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update(CarouselFormRequest $request, $id)
    {

        $this->carouselRepository->update($request,$id);
        return \Redirect::route('carousel.index')->with('message', 'updated carousel image!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        Carousel::findOrFail($id)->delete();
        return \Redirect::route('carousel.index')->with('message', 'deleted carousel image!');

    }
    //
}

resources/views/dashboard/carousel/edit.blade.php
@extends('dashboard')
@section('content')

    <div id="page-wrapper">

        <div class="container-fluid">

            <!-- Page Heading -->
            <div class="row">
                @if (count($errors) > 0)
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="alert alert-danger alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert"
                                        aria-hidden="true">&times;</button>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                @endif

                <div class="col-lg-12">
                    <h1 class="page-header">
                        Carousel
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-dashboard"></i> <a href="{{route('dashboard')}}">Dashboard</a>
                        </li>
                        <li class="active">
                            Carousel
                        </li>
                    </ol>

                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-6">
                    @if(isset($carousel))

                        {!! Form::model($carousel, ['url' => '/carousel/'.$carousel->id, 'method'=>'patch','files' => true])  !!}
                    @else
                        {{Form::open(['route' => 'carousel.store','files' => true])}}
                    @endif

                    <div class="form-group" style="padding-bottom: 5%">
                        {{ Form::label('Title') }}
                        {!! Form::text('title', null,
                        array('class'=>'form-control','placeholder'=>'e.g 50 x 100 plots')) !!}
                    </div>

                    <div class="form-group" style="padding-bottom: 5%">
                        {{ Form::label('Description') }}
                        {!! Form::text('description', null,
                        array('class'=>'form-control','placeholder'=>'Located 3km from Longonot township and 400m from the highway')) !!}
                    </div>


                    <div class="form-group" style="padding-bottom: 5%">
                        {{ Form::label('Image') }}
                        {!!Form::file('photo',
                        array('class'=>'form-control','placeholder'=>'land image')) !!}
                    </div>

                    <div class="form-group" style="padding-bottom: 15%">
                        {{      Form::submit( 'Submit!',array('class'=>"btn btn-success"))}}
                    </div>

                    {!! Form::close()  !!}


                </div>
            </div>


            <!-- /.row -->

        </div>
        <!-- /.container-fluid -->

    </div>


    <!-- /#page-wrapper -->

@endsection

@section('script')

    <script src="/js/tmce/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({selector: 'textarea'});</script>
@endsection

resources/views/dashboard/carousel/show.blade.php
@extends('dashboard')
@section('content')

    <div id="page-wrapper">

        <div class="container-fluid">
            @if(Session::has('message'))
                <div class="row">
                    <div class="col-lg-12">
                        <div class="alert alert-info alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert"
                                    aria-hidden="true">&times;</button>
                            <ul>

                                <li>{{ Session::get('message') }}</li>

                            </ul>
                        </div>
                    </div>
                </div>
        @endif
        <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        Carousel
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-dashboard"></i> <a href="{{route('dashboard')}}">Dashboard</a>
                        </li>

                        <li class="active">
                            Carousel
                        </li>
                    </ol>
                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">

                    <a href="{{ route('carousel.create') }}">
                        <button type="submit" class="btn btn-success">Add Carousel Item</button>
                    </a>
                </div>
            </div>
            <div class="row">
                @foreach($carousels as $carousel)
                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-block">
                                <h3 class="card-title">Title: {{$carousel->title}}</h3>
                                <img src="{{route('images',$carousel->image)}}" alt="Card image cap" height="50%"
                                     width="100%">
                                <h4 class="card-subtitle mb-2">Description</h4>
                                <p class="card-text">{!! $carousel->description !!}</p>

                                <a href="{{route('carousel.edit',$carousel->id)}}" class="card-link center"
                                   data-toggle="tooltip" title="Edit" style="color: #00a65a"><i
                                            class="fa fa-pencil-square-o fa-2x"> &nbsp;</i></a>
                                <a href="" data-toggle="modal" data-target="#delete-modal"
                                   class="card-link delete_director "
                                   id="{{$carousel->id}}"
                                   name="{{$carousel->title}}"
                                   data-toggle="tooltip" title="Delete" style="color: red"><i class="fa fa-trash fa-2x"
                                                                                              aria-hidden="true"></i>
                                </a>
                                <hr>

                            </div>
                        </div>
                    </div>
                @endforeach
            </div>

        </div>
    </div>


@endsection

<!--modal-->
<div id="delete-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Confirm Delete</h4>
            </div>
            <div class="modal-body edit-content">
                ...
            </div>
            <div class="modal-footer">
                <form id="form_delete" method="POST">
                    <input type="hidden" name="_method" value="DELETE"/>
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <button type="button" style="width: 20%" class="btn btn-success vertical-align"
                            data-dismiss="modal">No
                    </button>
                    <button type="submit" style="width: 20%" class="btn btn-danger">Yes</button>

                </form>

            </div>
        </div>
    </div>
</div>
<!--modal-->
@section('script')
    <script>
        $('#delete-modal').on('show.bs.modal', function (e) {

            var $modal = $(this),
                    esseyId = e.relatedTarget.id;
            name = e.relatedTarget.name;

            $modal.find('.edit-content').html("Are you sure you want to delete " + name + 'image ?');
            $modal.find('#form_delete').attr("action", "/carousel/" + esseyId);


        })
    </script>
@endsection