app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
    Route::get('/', 'PagesController@index');
    Route::get('About', 'PagesController@about');
    Route::get('Contacts', ['as' => 'contact', 'uses' => 'PagesController@contacts']);

    Route::post('Contacts', ['as' => 'contact_store', 'uses' => 'PagesController@store']);
    Route::get('Why-us', 'PagesController@why_us');

    Route::get('Properties', 'PagesController@properties');

    Route::get('edit', 'PagesController@edit');

    Route::get('images/{filename}', 'PropertyController@showImage')->where('filename', '(.*)')->name('images');
    // Authentication routes...
    Route::get('auth/login', 'Auth\AuthController@getLogin')->name('login');
    Route::post('auth/login', 'Auth\AuthController@postLogin')->name('login');


    // Registration routes...
    Route::get('/auth/register', 'Auth\AuthController@getRegister')->name('register');
    Route::post('/auth/register', 'Auth\AuthController@postRegister')->name('register');

    //reset password
    Route::get('password/reset/{token}', 'Auth\PasswordController@getReset')->name('reset');
    Route::post('password/reset', 'Auth\PasswordController@postReset')->name('reset');

    // Password reset link request routes...
    Route::get('password/email', 'Auth\PasswordController@getEmail')->name('email_password_reset_link');
    Route::post('password/email', 'Auth\PasswordController@postEmail')->name('email_password_reset_link');
});

Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/dashboard', 'PagesController@dashboard')->name('dashboard');
    Route::get('/dashboard/contacts', 'PagesController@viewContacts')->name('dashboard_contacts');
    Route::get('/dashboard/contacts/delete/{id}', 'PagesController@destroy')->name('dashboard_contacts_delete');
    Route::resource('/directors', 'DirectorController');
    Route::resource('/properties', 'PropertyController');
    Route::resource('/company', 'CompanyController');
    Route::resource('/carousel', 'CarouselController');
    Route::get('auth/logout', 'Auth\AuthController@getLogout')->name('logout');

});

app/Director.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model as Eloquent;

class Director extends Eloquent
{

    protected $table = "directors";
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'title', 'description',
    ];


}

app/Http/Controllers/DirectorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Director;
use App\Http\Requests\DirectorsFormRequest;

class DirectorController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view('dashboard.directors.show')->with(['directors' => Director::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('dashboard.directors.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(DirectorsFormRequest $request)
    {
        Director::create($request->all());
        return \Redirect::route('directors.index')->with('message', 'added director!');


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $user = Director::findOrFail($id);
        return view('dashboard.directors.edit')->with(['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update(DirectorsFormRequest $request, $id)
    {
        Director::findOrFail($id)->update($request->all());
        return \Redirect::route('directors.index')->with('message', 'updated director!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        Director::findOrFail($id)->delete();
        return \Redirect::route('directors.index')->with('message', 'deleted director!');

    }

}

resources/views/dashboard/directors/default_form.blade.php
@extends('dashboard')
@section('content')

    <div id="page-wrapper">

        <div class="container-fluid">

            <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        Forms
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-dashboard"></i> <a href="index.html">Dashboard</a>
                        </li>
                        <li class="active">
                            <i class="fa fa-edit"></i> Forms
                        </li>
                    </ol>
                </div>
            </div>
            <!-- /.row -->


            <div class="row">
                <div class="col-lg-6">

                    <form role="form">

                        <div class="form-group">
                            <label>Text Input</label>
                            <input class="form-control">
                            <p class="help-block">Example block-level help text here.</p>
                        </div>

                        <div class="form-group">
                            <label>Text Input with Placeholder</label>
                            <input class="form-control" placeholder="Enter text">
                        </div>

                        <div class="form-group">
                            <label>Static Control</label>
                            <p class="form-control-static">email@example.com</p>
                        </div>

                        <div class="form-group">
                            <label>File input</label>
                            <input type="file">
                        </div>

                        <div class="form-group">
                            <label>Text area</label>
                            <textarea class="form-control" rows="3"></textarea>
                        </div>

                        <div class="form-group">
                            <label>Checkboxes</label>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="">Checkbox 1
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="">Checkbox 2
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="">Checkbox 3
                                </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Inline Checkboxes</label>
                            <label class="checkbox-inline">
                                <input type="checkbox">1
                            </label>
                            <label class="checkbox-inline">
                                <input type="checkbox">2
                            </label>
                            <label class="checkbox-inline">
                                <input type="checkbox">3
                            </label>
                        </div>

                        <div class="form-group">
                            <label>Radio Buttons</label>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1"
                                           checked>Radio 1
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios2" value="option2">Radio 2
                                </label>
                            </div>
                            <div class="radio">
                                <label>
                                    <input type="radio" name="optionsRadios" id="optionsRadios3" value="option3">Radio 3
                                </label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Inline Radio Buttons</label>
                            <label class="radio-inline">
                                <input type="radio" name="optionsRadiosInline" id="optionsRadiosInline1" value="option1"
                                       checked>1
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="optionsRadiosInline" id="optionsRadiosInline2"
                                       value="option2">2
                            </label>
                            <label class="radio-inline">
                                <input type="radio" name="optionsRadiosInline" id="optionsRadiosInline3"
                                       value="option3">3
                            </label>
                        </div>

                        <div class="form-group">
                            <label>Selects</label>
                            <select class="form-control">
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Multiple Selects</label>
                            <select multiple class="form-control">
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                                <option>4</option>
                                <option>5</option>
                            </select>
                        </div>

                        <button type="submit" class="btn btn-default">Submit Button</button>
                        <button type="reset" class="btn btn-default">Reset Button</button>

                    </form>

                </div>
                <div class="col-lg-6">
                    <h1>Disabled Form States</h1>

                    <form role="form">

                        <fieldset disabled>

                            <div class="form-group">
                                <label for="disabledSelect">Disabled input</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="Disabled input"
                                       disabled>
                            </div>

                            <div class="form-group">
                                <label for="disabledSelect">Disabled select menu</label>
                                <select id="disabledSelect" class="form-control">
                                    <option>Disabled select</option>
                                </select>
                            </div>

                            <div class="checkbox">
                                <label>
                                    <input type="checkbox">Disabled Checkbox
                                </label>
                            </div>

                            <button type="submit" class="btn btn-primary">Disabled Button</button>

                        </fieldset>

                    </form>

                    <h1>Form Validation</h1>

                    <form role="form">

                        <div class="form-group has-success">
                            <label class="control-label" for="inputSuccess">Input with success</label>
                            <input type="text" class="form-control" id="inputSuccess">
                        </div>

                        <div class="form-group has-warning">
                            <label class="control-label" for="inputWarning">Input with warning</label>
                            <input type="text" class="form-control" id="inputWarning">
                        </div>

                        <div class="form-group has-error">
                            <label class="control-label" for="inputError">Input with error</label>
                            <input type="text" class="form-control" id="inputError">
                        </div>

                    </form>

                    <h1>Input Groups</h1>

                    <form role="form">

                        <div class="form-group input-group">
                            <span class="input-group-addon">@</span>
                            <input type="text" class="form-control" placeholder="Username">
                        </div>

                        <div class="form-group input-group">
                            <input type="text" class="form-control">
                            <span class="input-group-addon">.00</span>
                        </div>

                        <div class="form-group input-group">
                            <span class="input-group-addon"><i class="fa fa-eur"></i></span>
                            <input type="text" class="form-control" placeholder="Font Awesome Icon">
                        </div>

                        <div class="form-group input-group">
                            <span class="input-group-addon">$</span>
                            <input type="text" class="form-control">
                            <span class="input-group-addon">.00</span>
                        </div>

                        <div class="form-group input-group">
                            <input type="text" class="form-control">
                            <span class="input-group-btn"><button class="btn btn-default" type="button"><i
                                            class="fa fa-search"></i></button></span>
                        </div>

                    </form>

                    <p>For complete documentation, please visit <a href="http://getbootstrap.com/css/#forms">Bootstrap's
                            Form Documentation</a>.</p>

                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- /#page-wrapper -->

@endsection

resources/views/dashboard/directors/edit.blade.php
@extends('dashboard')
@section('content')

    <div id="page-wrapper">

        <div class="container-fluid">

            <!-- Page Heading -->
            <div class="row">
                @if (count($errors) > 0)
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="alert alert-danger alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert"
                                        aria-hidden="true">&times;</button>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                @endif

                <div class="col-lg-12">
                    <h1 class="page-header">
                        Forms
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-dashboard"></i> <a href="{{route('dashboard')}}">Dashboard</a>
                        </li>
                        <li class="active">
                            Directors
                        </li>
                    </ol>

                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-6">
                    @if(isset($user))

                        {!! Form::model($user, ['url' => '/directors/'.$user->id, 'method'=>'patch'])  !!}
                    @else
                        {{Form::open(['route' => 'directors.store'])}}
                    @endif

                    <div class="form-group">
                        {{ Form::label('Name') }}
                        {!! Form::text('name', null,
                        array('class'=>'form-control','placeholder'=>'Directors full  name*')) !!}
                    </div>
                    <div class="form-group">
                        {{ Form::label('Title') }}
                        {!! Form::text('title', null,
                        array('class'=>'form-control','placeholder'=>'Directors title*')) !!}
                    </div>


                    <div class="form-group">
                        {{ Form::label('Description') }}
                        {!! Form::textArea('description', null,
                        array('class'=>'form-control','placeholder'=>'Directors description i.e past achievements*')) !!}
                    </div>

                    <div class="form-group">
                        {{      Form::submit( 'Submit!',array('class'=>"btn btn-success"))}}
                    </div>

                        {!! Form::close()  !!}


                </div>
            </div>


            <!-- /.row -->

        </div>
        <!-- /.container-fluid -->

    </div>


    <!-- /#page-wrapper -->

@endsection

resources/views/dashboard/directors/show.blade.php
@extends('dashboard')
@section('content')

    <div id="page-wrapper">

        <div class="container-fluid">
            @if(Session::has('message'))
                <div class="row">
                    <div class="col-lg-12">
                        <div class="alert alert-info alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert"
                                    aria-hidden="true">&times;</button>
                            <ul>

                                <li>{{ Session::get('message') }}</li>

                            </ul>
                        </div>
                    </div>
                </div>
        @endif
        <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        Directors
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-dashboard"></i> <a href="{{route('dashboard')}}">Dashboard</a>
                        </li>

                        <li class="active">
                            Directors
                        </li>
                    </ol>
                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">

                    <a href="{{ route('directors.create') }}">
                        <button type="submit" class="btn btn-success">Add Director</button>
                    </a>
                </div>
            </div>
            <div class="row">
                @foreach($directors as $index=> $director)
                    @if($index%2!=0)
                        <div class="row">
                            @endif
                            <div class="col-lg-6">
                                <div class="card">
                                    <div class="card-block">
                                        <h3 class="card-title">  {{$director->name}}</h3>
                                        <h4 class="card-subtitle mb-2 text-muted">{{$director->title}}</h4>
                                        <h5 class="card-subtitle mb-2">Summary</h5>
                                        <p class="card-text">{{$director->description}}</p>
                                        </i> <a href="{{route('directors.edit',$director->id)}}"
                                                class="card-link center"
                                                data-toggle="tooltip" title="Edit" style="color: #00a65a"><i
                                                    class="fa fa-pencil-square-o fa-2x"> &nbsp;</i></a>
                                        <a href="" data-toggle="modal" data-target="#delete-modal"
                                           class="card-link delete_director "
                                           id="{{$director->id}}"
                                           name="{{$director->name}}"
                                           data-toggle="tooltip" title="Delete" style="color: red"><i
                                                    class="fa fa-trash fa-2x"
                                                    aria-hidden="true"></i>
                                        </a>

                                    </div>
                                </div>
                            </div>
                            @if($index%2!=0)
                        </div>
                    @endif
                @endforeach
            </div>

        </div>
    </div>


@endsection

<!--modal-->
<div id="delete-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Confirm Delete</h4>
            </div>
            <div class="modal-body edit-content">
                ...
            </div>
            <div class="modal-footer">
                <form id="form_delete" method="POST">
                    <input type="hidden" name="_method" value="DELETE"/>
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <button type="button" style="width: 20%" class="btn btn-success vertical-align"
                            data-dismiss="modal">No
                    </button>
                    <button type="submit" style="width: 20%" class="btn btn-danger">Yes</button>

                </form>

            </div>
        </div>
    </div>
</div>
<!--modal-->
@section('script')
    <script>
        $('#delete-modal').on('show.bs.modal', function (e) {

            var $modal = $(this),
                    esseyId = e.relatedTarget.id;
            name = e.relatedTarget.name;

            $modal.find('.edit-content').html("Are you sure you want to delete " + name + '?');
            $modal.find('#form_delete').attr("action", "/directors/" + esseyId);


        })
    </script>
@endsection