app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    //
    Route::get('/', 'PagesController@index');
    Route::get('About', 'PagesController@about');
    Route::get('Contacts', ['as' => 'contact', 'uses' => 'PagesController@contacts']);

    Route::post('Contacts', ['as' => 'contact_store', 'uses' => 'PagesController@store']);
    Route::get('Why-us', 'PagesController@why_us');

    Route::get('Properties', 'PagesController@properties');

    Route::get('edit', 'PagesController@edit');

    Route::get('images/{filename}', 'PropertyController@showImage')->where('filename', '(.*)')->name('images');
    // Authentication routes...
    Route::get('auth/login', 'Auth\AuthController@getLogin')->name('login');
    Route::post('auth/login', 'Auth\AuthController@postLogin')->name('login');


    // Registration routes...
    Route::get('/auth/register', 'Auth\AuthController@getRegister')->name('register');
    Route::post('/auth/register', 'Auth\AuthController@postRegister')->name('register');

    //reset password
    Route::get('password/reset/{token}', 'Auth\PasswordController@getReset')->name('reset');
    Route::post('password/reset', 'Auth\PasswordController@postReset')->name('reset');

    // Password reset link request routes...
    Route::get('password/email', 'Auth\PasswordController@getEmail')->name('email_password_reset_link');
    Route::post('password/email', 'Auth\PasswordController@postEmail')->name('email_password_reset_link');
});

Route::group(['middleware' => ['web','auth']], function () {
    Route::get('/dashboard', 'PagesController@dashboard')->name('dashboard');
    Route::get('/dashboard/contacts', 'PagesController@viewContacts')->name('dashboard_contacts');
    Route::get('/dashboard/contacts/delete/{id}', 'PagesController@destroy')->name('dashboard_contacts_delete');
    Route::resource('/directors', 'DirectorController');
    Route::resource('/properties', 'PropertyController');
    Route::resource('/company', 'CompanyController');
    Route::resource('/carousel', 'CarouselController');
    Route::get('auth/logout', 'Auth\AuthController@getLogout')->name('logout');

});

app/Company.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model as Eloquent;

class Company extends Eloquent
{

    protected $table = "company";
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'contains', 'title', 'particulars'
    ];

}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\CompanyFormRequest;

class CompanyController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $missions= Company::where('title','!=','Values')->get();
        $values= Company::where('title','Values')->get();
        return view('dashboard.company.show')->with(['missions' => $missions,'values'=>$values]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('dashboard.company.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(CompanyFormRequest $request)
    {
        Company::create($request->all());
        return \Redirect::route('company.index')->with('message', 'added company data!');


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $company = Company::findOrFail($id);
        return view('dashboard.company.edit')->with(['company' => $company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int $id
     * @return Response
     */
    public function update(CompanyFormRequest $request, $id)
    {
        Company::findOrFail($id)->update($request->all());
        return \Redirect::route('company.index')->with('message', 'updated director!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        Company::findOrFail($id)->delete();
        return \Redirect::route('company.index')->with('message', 'deleted director!');

    }


}

resources/views/dashboard/company/edit.blade.php
@extends('dashboard')
@section('content')

    <div id="page-wrapper">

        <div class="container-fluid">

            <!-- Page Heading -->
            <div class="row">
                @if (count($errors) > 0)
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="alert alert-danger alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert"
                                        aria-hidden="true">&times;</button>
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                @endif

                <div class="col-lg-12">
                    <h1 class="page-header">
                        Properties
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-dashboard"></i> <a href="{{route('dashboard')}}">Dashboard</a>
                        </li>
                        <li class="active">
                            Properties
                        </li>
                    </ol>

                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    @if(isset($company))

                        {!! Form::model($company, ['url' => '/company/'.$company->id, 'method'=>'patch'])  !!}
                    @else
                        {{Form::open(['route' => 'company.store','files' => true])}}
                    @endif

                    <div class="form-group">
                        {{ Form::label('Title') }}
                        {!! Form::text('title', null,
                        array('class'=>'form-control','placeholder'=>'Mission')) !!}
                    </div>
                        <div class="form-group">
                            {{ Form::label('Name') }}
                            {!! Form::text('contains', null,
                            array('class'=>'form-control','placeholder'=>'Integrity')) !!}
                        </div>
                    <div class="form-group">
                        {{ Form::label('Description') }}
                        {!! Form::textArea('particulars', null,
                        array('class'=>'form-control','placeholder'=>'a little description of the Company attribute*')) !!}
                    </div>



                    <div class="form-group">
                        {{      Form::submit( 'Submit!',array('class'=>"btn btn-success"))}}
                    </div>

                    {!! Form::close()  !!}


                </div>
            </div>


            <!-- /.row -->

        </div>
        <!-- /.container-fluid -->

    </div>


    <!-- /#page-wrapper -->

@endsection

@section('script')

    <script src="/js/tmce/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({selector: 'textarea'});</script>
@endsection

resources/views/dashboard/company/show.blade.php
@extends('dashboard')
@section('content')

    <div id="page-wrapper">

        <div class="container-fluid">
            @if(Session::has('message'))
                <div class="row">
                    <div class="col-lg-12">
                        <div class="alert alert-info alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert"
                                    aria-hidden="true">&times;</button>
                            <ul>

                                <li>{{ Session::get('message') }}</li>

                            </ul>
                        </div>
                    </div>
                </div>
        @endif
        <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        Company
                    </h1>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-dashboard"></i> <a href="{{route('dashboard')}}">Dashboard</a>
                        </li>

                        <li class="active">
                            Company
                        </li>
                    </ol>
                </div>
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">

                    <a href="{{ route('company.create') }}">
                        <button type="submit" class="btn btn-success">Add Company value</button>
                    </a>
                </div>
            </div>
            <div class="row">


                <div class="col-lg-6">
                    @foreach($missions as $mission)

                        <div class="card">
                            <div class="card-block">
                                <h3 class="card-title">  {{$mission->contains}}</h3>
                                {{--<h4 class="card-subtitle mb-2 text-muted">{{$mission->contains}}</h4>--}}
                                <h5 class="card-subtitle mb-2">Description</h5>
                                <p class="card-text">{!! $mission->particulars !!}</p>
                                </i> <a href="{{route('company.edit',$mission->id)}}"
                                        class="card-link center"
                                        data-toggle="tooltip" title="Edit" style="color: #00a65a"><i
                                            class="fa fa-pencil-square-o fa-2x"> &nbsp;</i></a>
                                <a href="" data-toggle="modal" data-target="#delete-modal"
                                   class="card-link delete_director "
                                   id="{{$mission->id}}"
                                   name="{{$mission->title}}"
                                   data-toggle="tooltip" title="Delete" style="color: red"><i
                                            class="fa fa-trash fa-2x"
                                            aria-hidden="true"></i>
                                </a>

                            </div>
                        </div>
                    @endforeach
                </div>

                <div class="col-lg-6">
                    <h3 class="card-title">  Values</h3>
                    @foreach($values as $value)

                        <div class="card">

                            <div class="card-block">
                                <h3 class="card-title">  {{$value->contains}}</h3>
                                {{--<h4 class="card-subtitle mb-2 text-muted">{{$mission->contains}}</h4>--}}
                                <h5 class="card-subtitle mb-2">Description</h5>
                                <p class="card-text">{{$value->particulars}}</p>
                                </i> <a href="{{route('company.edit',$value->id)}}"
                                        class="card-link center"
                                        data-toggle="tooltip" title="Edit" style="color: #00a65a"><i
                                            class="fa fa-pencil-square-o fa-2x"> &nbsp;</i></a>
                                <a href="" data-toggle="modal" data-target="#delete-modal"
                                   class="card-link delete_director "
                                   id="{{$value->id}}"
                                   name="{{$value->title}}"
                                   data-toggle="tooltip" title="Delete" style="color: red"><i
                                            class="fa fa-trash fa-2x"
                                            aria-hidden="true"></i>
                                </a>

                            </div>
                        </div>
                    @endforeach
                </div>


            </div>

        </div>
    </div>


@endsection

<!--modal-->
<div id="delete-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Confirm Delete</h4>
            </div>
            <div class="modal-body edit-content">
                ...
            </div>
            <div class="modal-footer">
                <form id="form_delete" method="POST">
                    <input type="hidden" name="_method" value="DELETE"/>
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <button type="button" style="width: 20%" class="btn btn-success vertical-align"
                            data-dismiss="modal">No
                    </button>
                    <button type="submit" style="width: 20%" class="btn btn-danger">Yes</button>

                </form>

            </div>
        </div>
    </div>
</div>
<!--modal-->
@section('script')
    <script>
        $('#delete-modal').on('show.bs.modal', function (e) {

            var $modal = $(this),
                    esseyId = e.relatedTarget.id;
            name = e.relatedTarget.name;

            $modal.find('.edit-content').html("Are you sure you want to delete " + name + '?');
            $modal.find('#form_delete').attr("action", "/company/" + esseyId);


        })
    </script>
@endsection